### PR TITLE
Update to JuMP v0.23

### LINKED ISSUE #222: Update to JuMP v0.23
We'll need to update our printing and our use of JuMP's nonlinear interface.

### PR DESCRIPTION
**Pull request by pulsipher**
Closes #222

### CODE REVIEW

**Comment by odow** [comment]
Sorry for the changes :) But I think they are an improvement

**Comment by pulsipher** [comment]
> Sorry for the changes :) But I think they are an improvement

No worries, this isn't too bad. I am just very excited that you secured funding to work on revamping the nonlinear side of things!

**Comment by pulsipher** [comment]
@odow I noticed that JuMP `v0.23` retains functions like `nl_expr_string` and `nl_constraint_string`. Were these intentionally not renamed with `nonlinear_`?

**Comment by odow** [comment]
> @odow I noticed that JuMP `v0.23` retains functions like `nl_expr_string` and `nl_constraint_string`. Were these intentionally not renamed with `nonlinear_`?

Ah damn. Looks like my find-and-replace-foo skills need work. I must have searched the documentation because these don't s. Can you open an issue with an example of how you're over-riding it? I'm not sure if it should be public. It takes a private argument:
https://github.com/jump-dev/JuMP.jl/blob/e7ffb7c01c94aecf6d6ad45f5ced6540499aa7e1/src/print.jl#L369-L390

**Comment by pulsipher** [comment]
> > @odow I noticed that JuMP `v0.23` retains functions like `nl_expr_string` and `nl_constraint_string`. Were these intentionally not renamed with `nonlinear_`?
> 
> Ah damn. Looks like my find-and-replace-foo skills need work. I must have searched the documentation because these don't s. Can you open an issue with an example of how you're over-riding it? I'm not sure if it should be public. It takes a private argument: https://github.com/jump-dev/JuMP.jl/blob/e7ffb7c01c94aecf6d6ad45f5ced6540499aa7e1/src/print.jl#L369-L390

I just use them in my tests as a quick and dirty way to check that I am creating nonlinear expressions correctly in the JuMP model. I do not extend them.

**Comment by pulsipher** [comment]
But yes, I can open an issue.

**Comment by pulsipher** [comment]
Opened https://github.com/jump-dev/JuMP.jl/issues/2892 to address this

**Pull request merged**
